name: metrics-system

services:
  questdb:
    image: questdb/questdb:7.3.3
    restart: unless-stopped
    ports:
      - 9000:9000 # REST API and Web Console
      - 9009:9009 # InfluxDB line protocol
      - 8812:8812 # Postgres wire protocol
      - 9003:9003 # Min health server
    volumes:
      - questdbstore:/var/lib/questdb
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafanastore:/var/lib/grafana

volumes:
  questdbstore:
  grafanastore:
